# Generated by Django 6.0.6 on 2026-07-19 15:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaGatilho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Alerta de Gatilho')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição (Opcional)')),
            ],
            options={
                'verbose_name': 'Alerta de Gatilho',
                'verbose_name_plural': 'Alertas de Gatilho',
            },
        ),
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome do Autor')),
                ('biografia', models.TextField(blank=True, null=True, verbose_name='Biografia')),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Gênero')),
            ],
            options={
                'verbose_name': 'Gênero',
                'verbose_name_plural': 'Gêneros',
            },
        ),
        migrations.CreateModel(
            name='Trope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome do Trope')),
            ],
            options={
                'verbose_name': 'Trope',
                'verbose_name_plural': 'Tropes',
            },
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('serie', models.CharField(blank=True, max_length=200, null=True, verbose_name='Série/Saga')),
                ('volume', models.IntegerField(blank=True, null=True, verbose_name='Volume/Número')),
                ('sinopse', models.TextField(verbose_name='Sinopse Oficial')),
                ('num_paginas', models.IntegerField(blank=True, null=True, verbose_name='Número de Páginas')),
                ('isbn', models.CharField(blank=True, max_length=13, null=True, unique=True, verbose_name='ISBN')),
                ('status_serie', models.CharField(blank=True, choices=[('andamento', 'Em Andamento'), ('completa', 'Completa')], max_length=20, null=True, verbose_name='Status da Série')),
                ('capa', models.ImageField(upload_to='capas_livros/', verbose_name='Capa do Livro')),
                ('criado_at', models.DateTimeField(auto_now_add=True, verbose_name='Cadastrado em')),
                ('alertas_gatilho', models.ManyToManyField(blank=True, related_name='livros', to='core.alertagatilho', verbose_name='Alertas de Gatilho')),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livros', to='core.autor', verbose_name='Autor')),
                ('generos', models.ManyToManyField(blank=True, related_name='livros', to='core.genero', verbose_name='Gêneros')),
                ('tropes', models.ManyToManyField(blank=True, related_name='livros', to='core.trope', verbose_name='Tropes')),
            ],
            options={
                'verbose_name': 'Livro',
                'verbose_name_plural': 'Livros',
                'ordering': ['serie', 'volume'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Biografia')),
                ('privacidade', models.CharField(choices=[('publico', 'Público'), ('privado', 'Privado'), ('amigos', 'Apenas Amigos')], default='publico', max_length=20, verbose_name='Privacidade da Conta')),
                ('seguindo', models.ManyToManyField(blank=True, related_name='seguidores', to='core.profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReadingEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('lendo', 'Lendo'), ('lido', 'Lido'), ('quero_ler', 'Quero Ler'), ('abandonado', 'Abandonado')], default='quero_ler', max_length=20, verbose_name='Status de Leitura')),
                ('avaliacao', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name='Avaliação')),
                ('resenha', models.TextField(blank=True, null=True, verbose_name='Resenha / Opinião Pessoal')),
                ('data_inicio', models.DateField(blank=True, null=True, verbose_name='Data de Início')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Data de Conclusão')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diarios', to='core.livro')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diarios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Diário de Leitura',
                'verbose_name_plural': 'Diários de Leitura',
                'unique_together': {('user', 'livro')},
            },
        ),
    ]
