# Generated by Django 6.0.6 on 2026-07-04 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome do Autor')),
                ('biografia', models.TextField(blank=True, null=True, verbose_name='Biografia')),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Gênero')),
            ],
            options={
                'verbose_name': 'Gênero',
                'verbose_name_plural': 'Gêneros',
            },
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('serie', models.CharField(blank=True, max_length=200, null=True, verbose_name='Série/Saga')),
                ('sinopse', models.TextField(verbose_name='Sinopse/Resenha')),
                ('avaliacao', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5, verbose_name='Avaliação')),
                ('capa', models.ImageField(upload_to='capas_livros/', verbose_name='Capa do Livro')),
                ('criado_at', models.DateTimeField(auto_now_add=True, verbose_name='Cadastrado em')),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livros', to='core.autor', verbose_name='Autor')),
                ('generos', models.ManyToManyField(related_name='livros', to='core.genero', verbose_name='Gêneros')),
            ],
            options={
                'verbose_name': 'Livro',
                'verbose_name_plural': 'Livros',
                'ordering': ['-criado_at'],
            },
        ),
    ]
