# Generated by Django 6.0.6 on 2026-07-04 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome do Trope')),
            ],
            options={
                'verbose_name': 'Trope',
                'verbose_name_plural': 'Tropes',
            },
        ),
        migrations.AddField(
            model_name='livro',
            name='num_paginas',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número de Páginas'),
        ),
        migrations.AddField(
            model_name='livro',
            name='tropes',
            field=models.ManyToManyField(related_name='livros', to='core.trope', verbose_name='Tropes'),
        ),
    ]
