# Generated by Django 6.0.6 on 2026-08-07 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_delete_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='aprovado',
            field=models.BooleanField(default=False, help_text='Se marcado, o livro aparecerá na busca global para todos os usuários.', verbose_name='Aprovado pela Moderação'),
        ),
        migrations.AddField(
            model_name='livro',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livros_cadastrados', to=settings.AUTH_USER_MODEL, verbose_name='Cadastrado por'),
        ),
    ]
