# Generated by Django 6.0.6 on 2026-07-06 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_trope_livro_num_paginas_livro_tropes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='livro',
            options={'ordering': ['serie', 'titulo'], 'verbose_name': 'Livro', 'verbose_name_plural': 'Livros'},
        ),
    ]
