# Generated by Django 6.0.6 on 2026-07-06 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_livro_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='livro',
            options={'ordering': ['serie', 'volume'], 'verbose_name': 'Livro', 'verbose_name_plural': 'Livros'},
        ),
        migrations.AddField(
            model_name='livro',
            name='volume',
            field=models.IntegerField(blank=True, null=True, verbose_name='Volume'),
        ),
    ]
