# Generated by Django 6.0.6 on 2026-07-09 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_livro_options_livro_volume'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='status_serie',
            field=models.CharField(blank=True, choices=[('andamento', 'Em Andamento'), ('completa', 'Completa')], max_length=20, null=True, verbose_name='Status da Série'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='volume',
            field=models.IntegerField(blank=True, null=True, verbose_name='Volume/Número'),
        ),
    ]
