# Generated by Django 6.0.6 on 2026-07-19 20:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Biografia')),
                ('privacidade', models.CharField(choices=[('publico', 'Público'), ('privado', 'Privado'), ('amigos', 'Apenas Amigos')], default='publico', max_length=20, verbose_name='Privacidade da Conta')),
                ('seguindo', models.ManyToManyField(blank=True, related_name='seguidores', to='usuarios.profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
