# Generated by Django 6.0.6 on 2026-08-07 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='atualizacoes_comunidade',
            field=models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não')], default='sim', max_length=3, verbose_name='Atualizações da comunidade'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='formato_leitura',
            field=models.CharField(choices=[('fisico', 'Físico'), ('digital', 'Digital'), ('fisico_digital', 'Físico e Digital'), ('audiobook', 'Audiobook')], default='fisico_digital', max_length=20, verbose_name='Formato preferido'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='historico_leitura',
            field=models.CharField(choices=[('publico', 'Público'), ('amigos', 'Apenas amigos'), ('privado', 'Apenas para mim')], default='privado', max_length=20, verbose_name='Histórico de leitura'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='incluir_sugestoes',
            field=models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não')], default='sim', max_length=3, verbose_name='Incluir sugestões de livros'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='lembretes_leitura',
            field=models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não')], default='sim', max_length=3, verbose_name='Lembretes de leitura'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='modo_leitura',
            field=models.CharField(choices=[('claro', 'Claro'), ('escuro', 'Escuro'), ('noturno', 'Noturno'), ('automatico', 'Automático (segue o sistema)')], default='automatico', max_length=20, verbose_name='Modo de leitura'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='mostrar_listas_publicamente',
            field=models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não')], default='sim', max_length=3, verbose_name='Mostrar listas publicamente'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='notificacoes_email',
            field=models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não')], default='sim', max_length=3, verbose_name='Notificações por e-mail'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='novos_lancamentos',
            field=models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não')], default='sim', max_length=3, verbose_name='Novos lançamentos e recomendações'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='perfil_publico',
            field=models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não')], default='sim', max_length=3, verbose_name='Perfil público'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='permitir_mensagens',
            field=models.CharField(choices=[('todos', 'Todos'), ('amigos_seguidores', 'Amigos e seguidores'), ('ninguem', 'Ninguém')], default='amigos_seguidores', max_length=20, verbose_name='Permitir mensagens'),
        ),
    ]
